
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir --upgrade -r requirements.txt

ADD . /app

# Copy the application code
COPY . .

# Expose the port FastAPI will run on
EXPOSE 8000

# Command to run the FastAPI server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
